require:
  - ts-node/register/transpile-only
sources:
  - name: <name>
    handler:
      postgraphile:
        connectionString: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
        cacheIntrospection: true
        appendPlugins:
          - '@graphile-contrib/pg-simplify-inflector'
        schemaName:
          - <schemaName>
        options:
          dynamicJson: true
          setofFunctionsContainNulls: false
          ignoreRBAC: false
          ignoreIndexes: false
          enableQueryBatching: true
          legacyRelations: omit
          subscriptions: true
          retryOnInitFail: true
          simpleCollections: both
          extendErrors:
            - errcode
          graphiql: false
          disableQueryLog: true
          jwtVerifyOptions:
            ignoreExpiration: false
          default_role: <defaultrole>
          jwt_secret: ${JWT_SECRET} 
          jwt_token: <jwt_token>